### PR TITLE
checkpatch: Ignore repeated words and attribute macros

### PR DESCRIPTION
**Pull request by Alex-deVis**
These options are too pedantic.

### CODE REVIEW

**Review by teodutu — COMMENTED** [review]
What's the problem with `PREFER_DEFINED_ATTRIBUTE_MACRO`? And `REPEATED_WORD` is useful for typing mistakes mistakes just like the one I've just made. I know it is a nuisance for some Makefiles, but I'd rather ignore it when it spits out false positives than disable it globally.

**Comment by Alex-deVis** [comment]
`PREFER_DEFINED_ATTRIBUTE_MACRO` seems to pedantic for what we are doing. You'd like some degree of flexibility when you are writing code. Nothing we cannot fix in place though.
`REPEATED_WORD` complains about `d` code, but if you are fine ignoring this false positive, go ahead and reject this.
```
WARNING:REPEATED_WORD: Possible repeated word: 'Mutex'
#18838: FILE: chapters/compute/synchronization/guides/race-condition/solution/d/race_condition_mutex_coarse.d:10:
+shared Mutex mutex;
```

**Comment by teodutu** [comment]
> `PREFER_DEFINED_ATTRIBUTE_MACRO` seems to pedantic for what we are doing. You'd like some degree of flexibility when you are writing code. Nothing we cannot fix in place though.

Do you have a case where this option caused us trouble?

> `REPEATED_WORD` complains about `d` code, but if you are fine ignoring this false positive, go ahead and reject this.
> 
> ```
> WARNING:REPEATED_WORD: Possible repeated word: 'Mutex'
> #18838: FILE: chapters/compute/synchronization/guides/race-condition/solution/d/race_condition_mutex_coarse.d:10:
> +shared Mutex mutex;
> ```

Just change the name of the variable to something else. This isn't a valid reason to remove this filter.

**Comment by razvand** [comment]
> > `PREFER_DEFINED_ATTRIBUTE_MACRO` seems to pedantic for what we are doing. You'd like some degree of flexibility when you are writing code. Nothing we cannot fix in place though.
> 
> Do you have a case where this option caused us trouble?
> 
> > `REPEATED_WORD` complains about `d` code, but if you are fine ignoring this false positive, go ahead and reject this.
> > ```
> > WARNING:REPEATED_WORD: Possible repeated word: 'Mutex'
> > #18838: FILE: chapters/compute/synchronization/guides/race-condition/solution/d/race_condition_mutex_coarse.d:10:
> > +shared Mutex mutex;
> > ```
> 
> Just change the name of the variable to something else. This isn't a valid reason to remove this filter.

@Alex-deVis , I agree with @teodutu . What we should actually be doing is having the ability to ignore certain checks for given commits. This typically involves a wrapper around `checkpath.pl`. This is what we are doing at Unikraft.

**Comment by Alex-deVis** [comment]
> What we should actually be doing is having the ability to ignore certain checks for given commits.

This would be great at some point, but for the moment @teodutu is right. Changing a few lines in the source code worked just fine. I'll close this for now, but you should create an issue for that, @razvand.

**Pull request closed without merging**
